version: '3'
services:
  # proxy 为服务名称，可自行改变
  proxy:
    # 拉取的镜像，这里也采用 alpine
    image: nginx:1.17.2-alpine
    # 设置容器名称，方便查看
    container_name: nginx-proxy
    # 设置 nginx 和宿主机的端口映射
    ports:
      - 80:8080
      # - 8081:4000 这里写 app2 的端口映射
    # 设置逻辑卷，用来与宿主机共享文件
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
  # 第一个应用，
  app1:
    # 刚上传的镜像
    image: lawler61/next-learn
    container_name: next-learn
  # app2:
    # image: lawler61/react-lighter
    # ...
